# Generated by Django 4.1.3 on 2022-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='Id заказа')),
                ('executor_id', models.BigIntegerField(verbose_name='Id исполнителя')),
                ('customer_id', models.BigIntegerField(verbose_name='Id заказчика')),
                ('status', models.SmallIntegerField(verbose_name='Статус заказа')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.CharField(max_length=4000, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
