# Generated by Django 4.1.3 on 2022-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.BigIntegerField(verbose_name='Id Исполнителя')),
                ('title', models.CharField(max_length=40, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=4000, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('currency', models.CharField(max_length=20, verbose_name='Валюта')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.IntegerField(default=0, verbose_name='Отметка нравится')),
            ],
            options={
                'verbose_name': 'Карточка услуги',
                'verbose_name_plural': 'Карточки услуг',
            },
        ),
    ]
