# Generated by Django 4.1.3 on 2022-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='users',
            name='orders',
            field=models.ManyToManyField(to='Order.order'),
        ),
    ]
