# Generated by Django 4.1.3 on 2022-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0001_initial'),
        ('users', '0002_delete_order_alter_users_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AlterField(
            model_name='users',
            name='bids',
            field=models.ManyToManyField(to='Bid.bid'),
        ),
    ]
